#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';

use Nano\Core\View\Template;
use Throwable;

$command = $argv[1] ?? 'help';

printf(
    "%s%s%s",
    "----------------------" . PHP_EOL,
    "| Nano Framework CLI |" . PHP_EOL,
    "----------------------" . PHP_EOL
);

switch ($command) {
    case 'clear':
        try {
            Template::clear();

            echo 'Cache limpo com sucesso';
        } catch (Throwable $e) {
            echo 'Erro ao limpar cache: ' . $e->getMessage();

            exit(1);
        }

        break;
    case 'help':
    default:
        echo 'clear => Limpa o cache do Template engine';
        break;
}

exit(0);
